Fix: Adiciona a biblioteca Swiper no CarouselPlugin
nossas/cms pull request #100
Opened 2023-08-30 16:39 UTC by miguelzinh3

### Contexto
Adiciona a biblioteca Swiper no CarouselPlugin

### Link da Tarefa/Issue
- https://app.asana.com/0/1161468210277385/1205367427032529/f

### Requisitos
- [x] Adiciona `swiper` para substituir o código JQuery do CarouselTemplate
- [x] Refatora o uso de estilos do Carousel
- [x] Refatora código para mostrar somente 1 item por slide no mobile

### Screenshots
![image](https://github.com/nossas/cms/assets/121839261/6627ae52-b149-42f1-a4d6-bd9afc5e8bb4)

### Notas de deploys
- `swiper` adicionado via CDN

2023-08-30 17:02 UTC, igr-santos requested changes

2023-08-30 17:02 UTC, igr-santos commented on app/eleicao/templates/eleicao/plugins/carousel.html
> +<script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
@miguelzinh3 o caso da tag **block** serve apenas para quando extendemos de templates, quando estamos trabalhando dentro do HTML de um plugin, usamos `{% addtoblock "js" %}` como [nesse exemplo](https://github.com/nossas/cms/blob/main/app/eleicao/templates/eleicao/plugins/voter_form.html#L40)

2023-08-30 17:02 UTC, igr-santos commented on app/tailwind/templates/tailwind.html
> +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />
@miguelzinh3 remover essa linha, porque você vai passar a usar a tag `{ % addtoblock "js" %}` no local correto, dentro do plugin

2023-08-30 17:07 UTC, miguelzinh3 commented on app/tailwind/templates/tailwind.html
> +  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />
done

2023-08-30 17:07 UTC, miguelzinh3 commented on app/eleicao/templates/eleicao/plugins/carousel.html
> +<script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script>
done

2023-08-30 21:26 UTC, igr-santos requested changes

2023-08-30 21:26 UTC, igr-santos commented on app/eleicao/templates/eleicao/includes/candidate_share.html
> +  <script src="{% static 'js/copy-to-clipboard.js' %}"></script>
@miguelzinh3 adicionar um block em um HTML que está sendo usado no include não me parece funcionar, podem ocorrer 2 problemas:

- Não funcionar porque não está usando o extends
- Funcionar mas sobrescrever o `{% block "footer_js" %}` HTML que usa esse include, nesse caso poderia ser o { `candidate_detail.html` talvez o melhor lugar pra colocar esse js seja no template que usa esse include

2023-08-31 13:37 UTC, igr-santos approved these changes

2023-08-31 17:22 UTC, merged