feat(votepeloclima): Implemented public profile candidate
nossas/cms pull request #242
Opened 2024-07-30 20:24 UTC by sergiomario

### Contexto
Criar página pública do perfil de Candidatura de acordo com o figma e utilizando os dados salvos da candidatura.

### Link da Tarefa/Issue
- [ ] [Visão pública do perfil do candidato](https://app.asana.com/0/1161468210277385/1207932744280961/f)

### Requisitos
- [ ] Perfil só pode ser acessado publicamente se estiver válido
- [ ] Deve ser possível compartilhar o perfil do Candidato nas redes sociais
- [ ] Uso de SLUG com nome público do candidato para URL do perfil

### Screenshots
TO DO

### Layout
TO DO

2024-08-12 14:36 UTC, igr-santos requested changes

2024-08-12 14:36 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/models.py
> +                self.slug = f"{slugify(self.ballot_name)}-{self.id}"
@miguelzinh3 @sergiomario não faz mais sentido concatenar o nome público da candidatura com o número da candidatura?

2024-08-12 14:36 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
> +<a class="btn btn-outline-light" href="{% url 'oauth:logout' %}">Sair</a>
@sergiomario @miguelzinh3 esse botão só aparece quando usuário está logado

2024-08-12 14:36 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/icons/pin.svg
@sergiomario @miguelzinh3 eu estou padronizando o uso de icones SVG como classes CSS, acho válido tentarmos fazer isso com esses ícones também

2024-08-12 14:36 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templatetags/social_media_tags.py
> +def url_parse(value: str, social_media_type):
@sergiomario @miguelzinh3 seria bom ter test unitário para essa template tag (testar possibilidades de URLs por exemplo que não vem com https)

2024-08-12 20:06 UTC, sergiomario commented on app/org_eleicoes/votepeloclima/candidature/models.py
> +                self.slug = f"{slugify(self.ballot_name)}-{self.id}"
Pode acontecer de pessoas com o mesmo nome de campanha em estados distintos terem o mesmo número, mas a probabilidade é baixa mesmo como conversamos. Vou seguir sugestão e alterar.

2024-08-14 17:28 UTC, igr-santos approved these changes

2024-08-14 17:29 UTC, merged