[Fix] Ajustes Perfil da Candidatura em mobile
nossas/cms pull request #268
Opened 2024-08-26 20:30 UTC by miguelzinh3

### Contexto

Ajustes no Perfil da Candidatura em Mobile, incluindo Carrossel, icones das redes sociais e adição do Footer no base.html

### Link da Tarefa/Issue
- [x] https://app.asana.com/0/1161468210277385/1208124898467252/f

### Requisitos
1. Bloco de compromissos: Adicionar propostas corretas, retirar o subtítulo e o botão de cadastro.

2. Diminuir fonte dos títulos para 32px, colocar em negrito e em caixa alta.

3. Configurar para que botões de rede social abrir em nova aba.

4. Compartilhar: Ajustar copy do bloco e texto de compartilhamento dos botões de acordo com o que está na tarefa.

5. Video: Retirar o subtítulo do bloco de vídeo.

6. Adicionar footer com o logo da campanha e descrição.

7. Ajustar espaçamento de informações: para ficar dividido em duas colunas de mesma largura.

8. Conferir cores pra garantir que está de acordo com o figma.

### Screenshots

2024-08-27 19:38 UTC, igr-santos requested changes

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
> +        <div class="g-col-12 g-col-sm-12 g-col-lg-8">
@miguelzinh3 se o padrão de tamanho é 12 e só muda quando é lg então fica redundante usar g-col-12 e g-col-sm-12, basta usar g-col-12 que ele vai atender essa condição até o breakpoint lg

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
> +                        {% if candidature.primary %}
@miguelzinh3 existe esse valor no modelo?

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
> +            <video controls src="{{ candidature.video.url }}" class="w-100"></video>
@miguelzinh3 testa diferentes formatos de video com essas configurações CSS

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
> +<script src="{% static '/js/copy-to-clipboard.js' %}" type="text/javascript"></script>
@miguelzinh3 nunca usar / no inicio da tag static, ela sempre vai esperar um caminho relativo, quando adiciona / você está definindo um caminho absoluto.

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/captcha.html
> +<div class="d-flex align-items-center justify-content-between">
@miguelzinh3 eu já havia configurado para ficar em coluna em telas menores e ficar em linha para telas maiores, confere se isso não deixou de funcionar

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html
> +      {% include "votepeloclima/logo-votepeloclima-sm.svg" %}
@miguelzinh3 trocar os nomes para logo navbar e logo footer, ou logo grande e logo pequena.

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html
> +        <img src="{% static "/imgs/logo-votepeloclima-lg.svg" %}" alt="Vote Pelo Clima">
@miguelzinh3 não pode usar / no inicio da definição dos arquivos estáticos

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html
> +            <img src="{% static "/imgs/logo-nossas.png" %}" alt="NOSSAS">
@miguelzinh3 remover a barra do inicio

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html
> +            <img src="{% static "/imgs/logo-clima-de-eleicao.png" %}" alt="Clima de Eleição">
@miguelzinh3 remover a barra do inicio

2024-08-27 19:38 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html
> +          <li><a class="text-white text-uppercase fw-bold" href="{% url 'oauth:login' %}" rel="noopener noreferrer">Login</a></li>
@miguelzinh3 jogar pra URL dashboard

2024-08-27 22:07 UTC, miguelzinh3 commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
> +            <video controls src="{{ candidature.video.url }}" class="w-100"></video>
coloquei um max-height de 600px!

2024-08-28 18:44 UTC, igr-santos approved these changes

2024-08-28 18:44 UTC, merged