feat(votepeloclima): included others informations session on dashboard
nossas/cms pull request #269
Opened 2024-08-26 22:11 UTC by sergiomario

### Contexto
Criação de uma sessão para outras informações na área de candidatura, como temas de política de privacidade e compartilhamento do perfil da pessoa candidata em redes sociais.

### Link da Tarefa/Issue
- [ ] [Adicionar conteúdo e ajustar links na sessão "outras informações"](https://app.asana.com/0/1161468210277385/1208113985648426/f)

<img width="869" alt="image (5)" src="https://github.com/user-attachments/assets/77be6c39-d4f5-4ab6-99b5-94bd907d3acd">

2024-08-27 01:31 UTC, miguelzinh3 approved these changes

2024-08-27 19:46 UTC, igr-santos requested changes

2024-08-27 19:46 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/templates/candidature/dashboard.html
> +                  {% with request.scheme|add:"://"|add:request.get_host as base_url %}
@sergiomario crie uma tag de contexto para montar a URL uma única vez e usar nas aplicações abaixo.

https://docs.djangoproject.com/en/5.1/howto/custom-template-tags/#inclusion-tags

2024-08-27 19:46 UTC, igr-santos commented on app/org_eleicoes/votepeloclima/candidature/static/js/copy-to-clipboard.js
> +    url = baseUrl + "/c/" + slug;
@sergiomario tentaria não montar a URL dentro do javascript mas já trazer ela montada no parametro da função JS

2024-09-03 18:59 UTC, igr-santos approved these changes

2024-09-03 19:14 UTC, merged